---
title: "Class exercise 2"
output:
  pdf_document: default
  html_document: default
date: '2022-04-15'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Using a vector create a variable with "Hello" "world!"

```{r}
print("Hello World!")
```
#My name

```{r}
my.name <-readline(prompt="Enter name: ")
print(paste("Hello,", my.name))
```
#Sequences

```{r}
seq1 = c(12,4,4,6,9,3)
seq1
seq2 = c(5,3,2,2,12,9)
seq2
print("Original Vectors are")
print(seq1)
print(seq2)
print("Product of two Vectors.")
seq3 = (seq1 *120)+(seq2 *145)
print(seq3)
```
#values>5

```{r}
seq1 = c(12,4,4,6,9,3)
seq2 = seq1[which(seq1>5)]
seq2
```
#matrix

```{r}
m1 <- matrix(1:12, nrow = 3, ncol = 4)
```
#length of matrix

```{r}
length(m1)
```
#create a data frame

```{r}
Employee <- c("Chef John Doe","BigChef Peter Gynn","BiggerChef Jolie Hope")
Salary <- c("21000","23400","26800")
Firstday <- as.Date(c('2010-11-01','2008-03-25','2007-03-14'))
data.frame(Employee,Salary,Firstday)
```

